// Seeded revision words, extracted verbatim from the original english.html
export const SEEDED_WORDS: string[][] = [
          ['Abandon', 'To leave something completely', 'He decided to abandon the plan because it was too risky.', 'The captain gave the order to abandon the ship.', 'Never abandon your dreams just because things get tough.'],
          ['Analyze', 'To examine something carefully', 'We need to analyze the problem before making a decision.', 'Scientists analyzed the data to find a cure.', 'You should analyze your spending habits to save money.'],
          ['Capacity', 'Ability or amount something can hold or do', 'This phone has enough capacity to store many apps.', 'The stadium has a seating capacity of 50,000 people.', 'She has an amazing capacity for learning new languages.'],
          ['Adorable', 'Very cute or lovable', 'The baby looks adorable in that dress.', 'That puppy playing in the park is absolutely adorable.', 'They live in an adorable little cottage by the sea.'],
          ['Advocate', 'To support or speak in favor of something', 'She strongly advocates regular exercise for good health.', 'The organization advocates for animal rights.', "As a lawyer, he must advocate for his client's best interests."],
          ['Brief', 'Short in time or length', 'Please give me a brief explanation of the plan.', 'We had a brief meeting to discuss the schedule.', 'Keep your introduction brief so we can start on time.'],
          ['Collaborate', 'To work together with others', 'We need to collaborate to solve this problem faster.', 'Designers and developers collaborate on this project.', 'Remote teams can collaborate easily using online tools.'],
          ['Commute', 'To travel regularly between home and work', 'She commutes to work every morning at 8 a.m.', 'Long commutes can be tiring.', 'He prefers working from home to avoid commuting.'],
          ['Compelling', 'Very interesting or convincing', 'The movie has a compelling story.', 'He gave a compelling argument during the meeting.', 'Her compelling speech motivated everyone.'],
          ['Consequence', 'A result or effect of an action', 'Every decision has a consequence.', 'Skipping practice had serious consequences for the team.', "He didn't think about the consequences before acting."],
          ['Constructive', 'Helpful and positive', 'She gave constructive feedback on my work.', "Let's have a constructive discussion instead of arguing.", 'His advice was honest but constructive.'],
          ['Contrast', 'To show the difference between two things', 'The teacher asked us to contrast the two ideas.', 'His calm nature contrasts with her energy.', 'The bright wall contrasts with the dark furniture.'],
          ['Crucial', 'Extremely important', 'Communication is crucial for team success.', "It's crucial to arrive on time for the interview.", 'Sleep is crucial for good health.'],
          ['Debate', 'A formal discussion with different opinions', 'The candidates will debate important issues tonight.', 'We had a long debate about the best strategy.', 'The topic sparked debate in the office.'],
          ['Determine', 'To decide or find out something', 'We need to determine the cause of the problem.', 'The test results will determine the next step.', 'She determined to improve her skills.'],
          ['Diligent', 'Hard-working and careful', 'She is diligent in completing her tasks on time.', 'A diligent student reviews notes every day.', 'His diligent effort paid off.'],
          ['Dispose', 'To get rid of something', 'Please dispose of the waste properly.', 'He disposed of the old files safely.', 'The company must dispose of chemicals carefully.'],
          ['Distinction', 'A clear difference between two things', 'There is a clear distinction between fact and opinion.', 'She graduated with distinction.', 'Understanding the distinction is important.'],
          ['Diverse', 'Including many different types', 'Our team is diverse in skills and experience.', 'The city has a diverse population.', 'A diverse diet is good for health.'],
          ['Dominant', 'Stronger or more powerful than others', 'English is the dominant language in the meeting.', 'The dominant team won the match easily.', 'His dominant personality stood out.'],
          ['Efficient', 'Working well without wasting time or effort', 'This machine is very efficient.', 'She found an efficient way to finish the task.', 'Efficient planning saves time.'],
          ['Elaborate', 'To explain in more detail', 'Could you elaborate on your idea?', 'She elaborated on the plan during the meeting.', 'He refused to elaborate further.'],
          ['Enthusiasm', 'Strong interest or excitement', 'She showed great enthusiasm for the project.', 'His enthusiasm motivated the team.', 'Children learn better with enthusiasm.'],
          ['Equivalent', 'Equal in value or meaning', 'One dollar is not equivalent to one euro.', 'This course is equivalent to a diploma.', 'The two answers are equivalent.'],
          ['Estimate', 'To roughly calculate or guess', 'Can you estimate the cost of the repair?', 'The engineer estimated the time needed.', "It's hard to estimate the final result."],
          ['Evidence', 'Proof that shows something is true', 'The police found clear evidence.', 'There is no evidence to support the claim.', 'Scientific decisions rely on evidence.'],
          ['Exaggerate', 'To make something seem bigger or better than it is', "Don't exaggerate the problem.", 'He tends to exaggerate his achievements.', 'She exaggerated the story for fun.'],
          ['Exceed', 'To go beyond a limit or expectation', 'The cost may exceed our budget.', 'His performance exceeded expectations.', 'Do not exceed the speed limit.'],
          ['Fanatic', 'A person with extreme enthusiasm', 'He is a fitness fanatic.', "She's a coffee fanatic.", 'Football fanatics filled the stadium.'],
          ['Fiercely', 'With great intensity or strength', 'They competed fiercely for the position.', 'She fiercely defended her opinion.', 'The sun was shining fiercely.'],
          ['Flexible', 'Able to change or adapt easily', 'My schedule is flexible this week.', 'She is flexible in her thinking.', 'This material is flexible and strong.'],
          ['Flinch', 'To react suddenly from fear or pain', "He didn't flinch during the injection.", 'She flinched at the loud noise.', 'Try not to flinch when the ball comes fast.'],
          ['Function', 'Purpose or the way something works', 'The phone stopped functioning properly.', 'What is the main function of this button?', 'The system must function smoothly.'],
          ['Generate', 'To produce or create something', 'The company generates new ideas regularly.', 'This machine generates electricity.', 'Good habits generate long-term success.'],
          ['Grind', 'To work very hard or reduce to small pieces', 'He is grinding to achieve his goals.', 'The machine grinds the coffee beans.', 'Success requires daily grind.'],
          ['Grit', 'Courage and determination', 'She showed grit during tough times.', 'Grit is essential for long-term success.', 'His grit helped him overcome failure.'],
          ['Guarantee', 'A promise that something will happen or work', 'I guarantee you will like this book.', 'Nothing can guarantee success overnight.', 'The product comes with a one-year guarantee.'],
          ['Guilty as charged', 'Admitting full responsibility', 'He smiled and said, "Guilty as charged."', 'I ate the last slice - guilty as charged.', 'She accepted the mistake, guilty as charged.'],
          ['Habit', 'A regular behavior or routine', 'Reading daily is a good habit.', 'Bad habits are hard to break.', 'He formed a habit of waking up early.'],
          ['Havoc', 'Widespread damage or chaos', 'The storm caused havoc in the city.', 'A small bug can wreak havoc in the system.', 'His mistake created havoc at work.'],
          ['Hesitate', 'To pause before doing something', "Don't hesitate to ask for help.", 'She hesitated before answering.', "I hesitate when I'm unsure."],
          ['I think I should, why not?', 'Expression used to decide casually', 'I think I should try it, why not?', 'He smiled and said, "I think I should apply, why not?"', "It's late, but I think I should go, why not?"],
          ['Identify', 'To recognize or find something', 'Please identify the main issue.', 'She identified the error quickly.', 'The police identified the suspect.'],
          ['Illustrate', 'To explain using examples or images', 'The teacher illustrated the concept with a diagram.', 'Let me illustrate this with an example.', 'The chart illustrates the growth clearly.'],
          ['Impact', 'The strong effect something has', 'The decision had a big impact on us.', 'Technology impacts daily life.', 'His words made a positive impact.'],
          ['Implement', 'To put a plan into action', 'The company will implement the new policy.', 'We need to implement this solution quickly.', 'The software update was implemented today.'],
          ['Imply', 'To suggest something without saying it directly', 'His tone implied dissatisfaction.', 'She implied that the deadline was missed.', 'The message implies urgency.'],
          ['Indicate', 'To show or point out', 'The data indicates growth.', 'The sign indicates the exit.', 'His behavior indicated stress.'],
          ['Initial', 'First or beginning stage', 'This is the initial step of the process.', 'My initial reaction was surprise.', 'The initial plan needs improvement.'],
          ['Insight', 'A deep or clear understanding', 'He gave valuable insight during the meeting.', 'This book provides insight into human behavior.', 'Experience brings insight.'],
          ['Interpret', 'To explain or understand meaning', 'She interpreted the data correctly.', 'People may interpret the message differently.', 'The lawyer interpreted the law clearly.'],
          ['Investigate', 'To examine something carefully to find facts', 'The police will investigate the case.', 'We need to investigate the issue further.', 'The report investigates market trends.'],
          ['Logical', 'Based on clear reasoning', 'His explanation was logical.', "Let's take a logical approach.", 'The conclusion seems logical.'],
          ['Maintain', 'To keep something in good condition or continue it', 'She maintains a healthy routine.', 'Please maintain silence in the hall.', 'The system must be maintained regularly.'],
          ['Majority', 'More than half of a group', 'The majority agreed with the decision.', 'A majority of voters supported the plan.', 'The majority opinion prevailed.'],
          ['Manage', 'To control or handle something successfully', 'She manages the team efficiently.', 'He learned how to manage stress.', 'Can you manage this task alone?'],
          ['Margin', 'The difference or extra amount', 'We won by a small margin.', 'There is little margin for error.', 'The profit margin increased this year.'],
          ['Modify', 'To make small changes', 'The plan was modified slightly.', 'We need to modify the design.', 'She modified her routine for better results.'],
          ['Negative', 'Harmful or unfavorable', 'The test result was negative.', 'Negative thinking affects confidence.', 'He received negative feedback.'],
          ['Objective', 'A goal or something not influenced by feelings', 'The main objective is growth.', 'Try to stay objective during discussions.', 'The report is objective and factual.'],
          ['Obtain', 'To get or acquire something', 'She obtained permission to leave early.', 'You can obtain information online.', 'He obtained a degree in engineering.'],
          ['Oppose', 'To disagree with or resist something', 'Many people oppose the decision.', 'She opposed the new policy.', 'The plan was strongly opposed.'],
          ['Overwhelm', 'To affect someone very strongly', 'The workload overwhelmed him.', 'She felt overwhelmed by emotions.', 'Too many choices can overwhelm people.'],
          ['Parallel', 'Side by side or similar in nature', 'The two roads run parallel.', 'His career runs parallel to his education.', 'The stories have parallel themes.'],
          ['Pardon me', 'A polite way to interrupt or apologize', 'Pardon me, could you repeat that?', 'Pardon me for being late.', 'Pardon me, may I pass?'],
          ['Perspective', 'A way of thinking or point of view', 'Try to see the issue from my perspective.', 'Travel changes your perspective.', 'Her perspective was valuable.'],
          ['Pinch-me moment', 'An unbelievable or very exciting experience', 'Getting the job felt like a pinch-me moment.', 'Winning the award was a pinch-me moment.', 'Being on stage was a real pinch-me moment.'],
          ['Precise', 'Exact and accurate', 'Please be precise with the details.', 'The measurements must be precise.', 'She gave a precise answer.'],
          ['Predict', 'To say what will happen in the future', 'Experts predict heavy rain tomorrow.', "It's hard to predict market trends.", 'The model predicts user behavior.'],
          ['Priority', 'Something more important than others', 'Health should be your top priority.', 'Meeting the deadline is a priority.', 'Family is my first priority.'],
          ['Proceed', 'To continue or move forward', 'We can proceed with the plan.', 'Please proceed carefully.', 'The meeting will proceed as scheduled.'],
          ['Prosperity', 'Success, wealth, or well-being', 'Education leads to prosperity.', 'The country enjoyed economic prosperity.', 'Hard work brings long-term prosperity.'],
          ['Pursuit', 'The act of trying to achieve something', 'Happiness is a lifelong pursuit.', 'He is in pursuit of excellence.', 'Knowledge is worth the pursuit.'],
          ['Quote', "To repeat someone's exact words", 'She quoted a famous author.', 'Let me quote the report.', 'He quoted the rule correctly.'],
          ['Reaction', 'A response to something', 'The news caused a strong reaction.', 'Her reaction was unexpected.', 'Observe the reaction carefully.'],
          ['Reckless', 'Careless and without thinking about consequences', 'His reckless driving caused an accident.', 'She made a reckless decision under pressure.', 'Reckless behavior can be dangerous.'],
          ['Reflect', 'To think deeply or show something clearly', 'I need time to reflect on my choices.', 'The mirror reflects light.', 'His actions reflect his values.'],
          ['Relevant', 'Closely connected or important to the topic', 'Please share relevant information only.', 'Experience is relevant for this job.', 'The data is not relevant anymore.'],
          ['Resolve', 'To find a solution or decide firmly', 'We need to resolve this issue quickly.', 'She resolved to improve her skills.', 'The conflict was finally resolved.'],
          ['Resources', 'Supplies or assets used to achieve something', 'The company lacks enough resources.', 'Human resources handle hiring.', 'We must use resources wisely.'],
          ['Scarcity', 'A shortage or lack of something', 'Water scarcity is a serious problem.', 'Scarcity increases prices.', 'The region suffers from food scarcity.'],
          ['Shivering', 'Shaking slightly because of cold, fear, or illness', 'She was shivering in the cold wind.', 'He started shivering after the fever.', 'The child stood there shivering.'],
          ['Significant', 'Important or having a noticeable effect', 'The project made significant progress.', 'There is a significant difference in results.', 'His contribution was significant.'],
          ['Solution', 'An answer to a problem', 'We finally found a solution.', 'There is no easy solution to this issue.', 'Technology offers smart solutions.'],
          ['Specific', 'Clear and exact', 'Please give specific details.', 'Be specific about your goals.', 'The instructions were very specific.'],
          ['Stability', 'The state of being steady or secure', 'Financial stability is important.', 'The company is working toward stability.', 'Emotional stability helps in tough times.'],
          ['Stay firm', 'To remain strong in your decision', 'Stay firm in your decision.', 'She stayed firm despite criticism.', 'You must stay firm under pressure.'],
          ['Strategy', 'A plan to achieve a goal', 'We need a strong strategy to win.', 'His business strategy worked well.', 'Planning is part of strategy.'],
          ['Sufficient', 'Enough for a purpose', 'Is this amount sufficient?', 'He has sufficient experience for the role.', 'Sleep is sufficient for recovery.'],
          ['Summary', 'A short version of main points', 'Give me a summary of the meeting.', 'The report includes a brief summary.', 'She wrote a clear summary.'],
          ['Suspend', 'To temporarily stop or pause', 'The meeting was suspended for 10 minutes.', 'His account was suspended.', 'The game was suspended due to rain.'],
          ['Transfer', 'To move something from one place to another', 'She transferred money to my account.', 'He requested a job transfer.', 'The data was transferred successfully.'],
          ['Typical', 'Normal or usual for someone or something', "It's typical of him to be late.", 'This weather is typical for winter.', 'That reaction is typical.'],
          ['Visible', 'Able to be seen clearly', 'The stars are visible tonight.', 'The results are clearly visible.', 'There was visible improvement.'],
          ['Self-sufficient', 'Able to take care of yourself without help', 'He became financially self-sufficient.', 'A self-sufficient person depends less on others.', 'The village is self-sufficient in food production.'],
          ['Vague', 'Not clear or specific', 'His explanation was vague.', 'Give me a clear answer, not something vague.', 'The instructions were too vague to follow.'],
          ['Crude', 'Rough, not refined, or offensive', 'His crude behavior shocked everyone.', 'The oil is still in crude form.', 'That was a crude joke.'],
          ['Boredom', 'The state of feeling uninterested or tired of something', 'Boredom can reduce productivity.', 'He left the meeting out of boredom.', 'Reading helps fight boredom.'],
          ['Drill', 'Repeated practice or training', 'We had a fire drill today.', 'Practice the drill until it becomes natural.', 'The coach made us repeat the drill.'],
          ['Automaticity', 'The ability to do something automatically without conscious effort', 'With practice, speaking English develops automaticity.', 'Typing daily improves automaticity.', 'Automaticity reduces mental effort.'],
          ['Cramming', 'Studying a lot in a short time before an exam', 'Cramming is not effective for long-term learning.', 'He was cramming all night before the test.', 'Avoid cramming and study consistently.'],
          ['Retention', 'The ability to remember information', 'Regular revision improves retention.', 'Sleep helps memory retention.', 'The training increased knowledge retention.'],
          ['Prolong', 'To make something last longer', "Don't prolong the meeting unnecessarily.", 'Medicine can prolong life.', 'He tried to prolong the discussion.'],
          ['Disguise', 'To hide the real appearance or truth', 'He wore glasses to disguise himself.', 'She disguised her feelings.', 'The spy used a disguise.'],
          ['Fatigue', 'Extreme tiredness', 'After work, he felt deep fatigue.', 'Fatigue affects performance.', 'Lack of sleep causes fatigue.'],
          ['Metrics', 'Measurements used to evaluate performance', 'The company tracks key metrics.', 'These metrics show user growth.', 'We use metrics to measure success.'],
          ['Burnout', 'Physical or mental exhaustion from prolonged stress', 'Long working hours can cause burnout.', 'She took a break to avoid burnout.', 'Burnout reduces productivity.'],
          ['Exhaustion', 'Extreme tiredness or fatigue', 'After the marathon, he felt total exhaustion.', 'Lack of rest leads to exhaustion.', 'She collapsed from exhaustion.'],
          ['Monologue', 'A long speech by one person', 'He gave a long monologue during the meeting.', 'The actor performed a powerful monologue.', "The teacher's monologue made the class quiet."],
          ['Tempered', 'Controlled or balanced', 'His anger was tempered by experience.', 'She gave a tempered response.', 'The leader showed tempered judgment.'],
          ['Embarrass yourself', 'To make yourself feel ashamed or awkward', "Don't embarrass yourself by lying.", 'He embarrassed himself by forgetting the speech.', "She didn't want to embarrass herself in public."],
          ['Deliberate', 'Done carefully and intentionally', 'It was a deliberate decision.', 'She spoke in a slow, deliberate way.', 'The mistake was not deliberate.'],
          ['Tiring', 'Causing fatigue or exhaustion', 'The long meeting was tiring.', 'Traveling all day is tiring.', 'The work became mentally tiring.'],
          ['Ritual', 'A repeated action done regularly', 'Morning exercise is his ritual.', 'They follow a ritual before the game.', 'Tea time became a daily ritual.'],
          ['Organic', 'Natural; not artificial or chemical', 'The farm grows organic vegetables.', 'She prefers organic food.', 'The growth was organic, not forced.'],
          ['Audacity', 'Bold courage, sometimes rude confidence', 'He had the audacity to question the manager.', 'Her audacity impressed everyone.', 'It took audacity to start the company.'],
          ['Pitfalls', 'Hidden problems or dangers in a situation', 'Every business has potential pitfalls.', 'Avoid the common pitfalls of investing.', 'The guide explained the pitfalls of the plan.'],
          ['Intimidate', 'To frighten or make someone feel less confident', 'His tone tried to intimidate the team.', "Don't let anyone intimidate you.", 'The large crowd can intimidate new speakers.'],
          ['Nudge', 'A gentle push or encouragement', 'She gave me a nudge to speak up.', 'The app nudges users to stay active.', 'He nudged the door open.'],
          ['So do I', 'Used to agree with a positive statement', 'I like coffee, so do I.', 'I enjoy coding, so do I.', 'I want to travel, so do I.'],
          ['So do you', 'Used to point out someone shares the same action or feeling', 'You like coffee, so do you.', 'You enjoy coding, so do you.', 'You want to travel, so do you.'],
          ['Intuition', 'Ability to understand something without conscious reasoning', 'Trust your intuition.', 'His intuition was correct.', 'Experience improves intuition.'],
          ['Bias', 'A tendency to favor one side unfairly', 'The report shows bias.', 'Avoid bias in decision-making.', 'Personal bias affects judgment.'],
          ['Distorts', 'Twists or changes the true meaning or shape', 'Bias distorts reality.', 'The lens distorts the image.', 'Emotion distorts judgment.'],
          ['Delusion', 'A false belief despite evidence', 'He lived under a delusion of success.', "It's a delusion to think effort isn't needed.", 'She had no delusion about the risks.'],
          ['Illusion', 'A false appearance or impression', 'It was just an illusion.', 'The magician created an illusion.', 'Success without effort is an illusion.'],
          ['Distort', 'To twist or change something from its true meaning', 'Media can distort facts.', "Don't let emotions distort your thinking.", 'The mirror distorts the image.'],
          ['Rapport', 'A close and positive relationship', 'She built strong rapport with clients.', 'Good teachers create rapport with students.', 'Rapport improves communication.'],
          ['Parallel (revise)', 'Similar or happening at the same time', 'His career runs parallel to his studies.', 'The two stories are parallel.', 'Their goals are parallel.'],
          ['Dilute', 'To make something weaker by adding more', 'The company diluted the product quality.', 'Add water to dilute the juice.', 'His message was diluted over time.'],
          ['Egocentric', 'Thinking only about yourself', 'He is too egocentric to listen to others.', 'Egocentric behavior harms relationships.', 'A leader should not be egocentric.'],
          ['Even though', 'Despite the fact that (used to show contrast)', 'Even though it was raining, we went out.', 'She smiled even though she was tired.', 'Even though he studied, the test was hard.'],
          ['Indispensable', 'Absolutely necessary or essential', 'Water is indispensable for life.', 'He is an indispensable member of the team.', 'Good communication is indispensable.'],
          ['Scattered', 'Spread out or not organized', 'His thoughts were scattered.', 'Books were scattered on the table.', 'The team looked scattered during the game.'],
          ['Overwhelmed', 'Feeling too much pressure or emotion', 'I felt overwhelmed with work.', 'She was overwhelmed by emotions.', 'Too many tasks can make you overwhelmed.'],
          ['Abundance', 'A very large quantity of something', 'There is an abundance of opportunities online.', 'The garden has an abundance of flowers.', 'We live in an age of information abundance.'],
          ['Vulnerable', 'Open to harm or damage', 'Children are vulnerable to illness.', 'He felt vulnerable after the loss.', 'Data can be vulnerable to attacks.'],
          ['Fragile', 'Easily broken or damaged', 'This glass is fragile.', 'Trust is fragile and easy to lose.', 'The situation is fragile right now.'],
          ['Leap', 'A big jump or sudden change', 'He took a leap of faith.', 'Technology made a big leap forward.', 'She leaped over the gap.'],
          ['Prudent', 'Wise and careful in decisions', "It's prudent to save money.", 'He made a prudent investment.', 'A prudent approach avoids risks.'],
          ['Disguises', 'Things used to hide true identity or appearance', 'He used disguises to avoid being recognized.', 'The spy carried multiple disguises.', 'Her emotions were hidden behind clever disguises.'],
          ['Fickle', 'Changing feelings or loyalty quickly', 'People can be fickle.', 'The weather here is very fickle.', 'His opinions are fickle.'],
          ['Amateurs', 'People who do something without professional skill', 'The competition included many amateurs.', 'Amateurs often learn by practice.', 'The event welcomed both amateurs and experts.'],
          ['Conscience', 'A sense of right and wrong', "His conscience didn't allow him to lie.", 'Listen to your conscience.', 'She acted according to her conscience.'],
          ['Redemption', 'The act of making something right after a mistake', 'This was his chance for redemption.', 'He worked hard for redemption.', 'The story is about redemption.'],
          ['Nuances', 'Small subtle differences or details', 'Language has many nuances.', 'He understands the nuances of the market.', 'Pay attention to small nuances.'],
          ['Cocky', 'Overconfident in a rude way', 'He sounded cocky during the interview.', "Don't be cocky after one success.", 'Her cocky attitude annoyed everyone.'],
          ['Captivating', 'Very attractive or interesting', 'She gave a captivating performance.', 'The story was captivating.', 'His speech was captivating.'],
          ['Profound', 'Very deep or meaningful', 'He made a profound statement.', 'The book had a profound impact on me.', 'Her words were simple but profound.'],
          ['Persuasive', 'Able to convince others', 'His argument was very persuasive.', 'She gave a persuasive presentation.', 'A persuasive message can influence people.'],
          ['Terrifying', 'Very scary or frightening', 'The movie was terrifying.', 'It was a terrifying experience.', 'The storm looked terrifying.'],
          ['Mediocrity', 'Average quality, not very good or bad', 'He refused to accept mediocrity.', 'The company moved beyond mediocrity.', 'Mediocrity limits growth.'],
          ['Rapport', 'A close and positive relationship', 'She built strong rapport with clients.', 'Good leaders create rapport with teams.', 'Rapport improves communication.'],
          ['Receptive', 'Willing to listen or accept new ideas', 'He is receptive to feedback.', 'The team was receptive to change.', 'Be receptive to new opportunities.'],
          ['Stimulation', 'Something that increases activity or interest', 'This game provides mental stimulation.', 'Exercise gives physical stimulation.', 'The discussion created intellectual stimulation.'],
          ['Reinforce', 'To strengthen or support something', 'Practice helps reinforce learning.', 'The teacher reinforced the concept with examples.', 'Positive feedback reinforces good behavior.'],
          ['Gratification', 'Pleasure or satisfaction', 'He delayed gratification to achieve success.', 'Instant gratification can be harmful.', 'Helping others gives deep gratification.'],
          ['Inevitable', 'Certain to happen', 'It was inevitable that he would succeed.', 'Change is inevitable.', 'The outcome became inevitable.'],
          ['Readiness', 'The state of being fully prepared', 'His readiness impressed the team.', 'We checked the system readiness.', 'Readiness is key before launching.'],
          ['Retrospective', 'Looking back at past events', 'The team held a retrospective meeting.', 'In retrospective, the decision was right.', 'The film is a retrospective of his career.'],
          ['Cognitive', 'Related to thinking or mental processes', 'Cognitive skills improve with practice.', 'The test measures cognitive ability.', 'Reading boosts cognitive development.'],
          ['Disguised', 'Hidden or changed to look different', 'His voice was disguised.', 'The truth was disguised in humor.', 'She disguised her feelings well.'],
          ['Dilute (revise)', 'To make something weaker', 'The message got diluted over time.', 'Add water to dilute the solution.', 'Too many features dilute the product focus.'],
          ['Vulnerable (revise)', 'Open to harm or risk', 'He felt vulnerable sharing his story.', 'Small businesses are vulnerable to market changes.', 'Data is vulnerable without security.'],
          ['Acknowledge', 'To accept or recognize something', 'He acknowledged his mistake.', "She acknowledged the team's effort.", 'Please acknowledge the email.'],
          ['Inevitable', 'Certain to happen', 'Change is inevitable.', 'It was inevitable that they would meet.', 'The result became inevitable.'],
          ['Perishable', 'Easily spoiled or damaged (especially food)', 'Milk is a perishable item.', 'Keep perishable goods in the fridge.', 'Fruits are highly perishable.'],
          ['Anticipate', 'To expect or prepare for something', 'We anticipate delays due to traffic.', 'She anticipated the question.', 'The team anticipates strong growth.'],
          ['Aggressive', 'Forceful or very determined', 'The company used an aggressive strategy.', 'He plays aggressive cricket.', 'Aggressive marketing increased sales.'],
          ['Adequate', 'Enough or satisfactory for a purpose', 'The resources are adequate for now.', 'He has adequate experience.', 'The room has adequate lighting.'],
          ['Assessment', 'The act of evaluating something', 'The teacher made an assessment of the work.', 'We need a risk assessment.', 'His performance assessment was positive.'],
          ['Association', 'A connection between people or ideas', 'There is a strong association between diet and health.', 'He joined a professional association.', 'The word has a negative association.'],
          ['Assure', 'To make someone confident or certain', 'I assure you everything will be fine.', 'She assured him of her support.', 'He assured the team of success.'],
          ['Barely', 'Only just or almost not', 'He barely passed the exam.', 'I could barely hear her.', 'They barely made it on time.'],
          ['Beside', 'Next to or by the side of', 'The bag is beside the chair.', 'She sat beside me.', 'The phone is beside your laptop.'],
          ['Bind', 'To tie or hold together', 'The contract will bind both parties.', 'She used rope to bind the box.', 'Strong values bind the team.'],
          ['Certainly', 'Without doubt or definitely', 'I will certainly help you.', 'She will certainly attend the meeting.', 'This is certainly a good idea.'],
          ['Coalition', 'A group formed for a common purpose', 'The parties formed a coalition.', 'A coalition of companies launched the project.', 'The coalition worked together to win.'],
          ['Collapse', 'To fall down suddenly or fail', 'The building collapsed after the fire.', 'The plan collapsed due to poor execution.', 'He collapsed from exhaustion.'],
          ['Commercial', 'Related to business or trade', 'This is a commercial project.', 'The area is mainly commercial.', 'They launched a new commercial campaign.'],
          ['Consciousness', 'Awareness of surroundings or thoughts', 'He lost consciousness after the fall.', 'Meditation improves consciousness.', 'She regained consciousness quickly.'],
          ['Conservative', 'Careful, traditional, or avoiding risk', 'He has conservative views.', 'The company took a conservative approach.', 'Investors prefer conservative strategies.'],
          ['Contemporary', 'Belonging to the present time', 'This is a contemporary issue.', 'She studies contemporary art.', 'The design looks modern and contemporary.'],
          ['Controversial', 'Causing disagreement or debate', 'The decision was controversial.', 'He made a controversial statement.', 'The topic is highly controversial.'],
          ['Call off', 'To cancel something', 'They called off the meeting.', 'The game was called off due to rain.', 'We had to call off the trip.'],
          ['Conventional', 'Based on usual practices or standards', 'This is a conventional approach.', 'He prefers conventional methods.', 'The idea is not conventional.'],
          ['Conviction', 'A strong belief or opinion', 'She spoke with conviction.', 'He has a strong conviction about success.', 'His conviction inspired others.'],
          ['Counselor', 'A person who gives advice or guidance', 'The counselor helped him make a decision.', 'She works as a school counselor.', 'Talk to a counselor if you need help.'],
          ['Critic', 'A person who judges or evaluates something', 'He is a film critic.', 'The critic gave a negative review.', 'She became a harsh critic of the plan.'],
          ['Crucial', 'Extremely important', 'This step is crucial for success.', 'Communication is crucial in teams.', 'Timing is crucial in this task.'],
          ['Democratic', 'Related to democracy or equal participation', 'The country follows a democratic system.', 'They made a democratic decision.', 'The process was fair and democratic.'],
          ['Depict', 'To show or represent something', 'The painting depicts a village.', 'The film depicts real events.', 'The chart depicts growth.'],
          ['Despite', 'In spite of something', 'Despite the rain, we continued.', 'She succeeded despite difficulties.', 'He smiled despite the pain.'],
          ['Discrimination', 'Unfair treatment of people', 'The law protects against discrimination.', 'She faced discrimination at work.', 'We must fight discrimination.'],
          ['Dispute', 'A disagreement or argument', 'The dispute lasted for months.', 'They settled the dispute peacefully.', 'A legal dispute started between the companies.'],
          ['Distinguish', 'To recognize differences between things', "It's hard to distinguish the twins.", 'Can you distinguish fact from opinion?', 'Experience helps distinguish good ideas.'],
          ['Effectively', 'In a successful or efficient way', 'She communicates effectively.', 'The team worked effectively together.', 'Time was used effectively.'],
          ['Embrace', 'To accept something willingly', 'She embraced the new opportunity.', 'We should embrace change.', 'He embraced his responsibilities.'],
          ['Enforcement', 'The act of making sure rules are followed', 'Strict enforcement of rules is necessary.', 'The law enforcement team arrived quickly.', 'Policy enforcement improved discipline.'],
          ['Enormous', 'Extremely large or huge', 'The company made enormous profits.', 'He has enormous potential.', 'The project requires enormous effort.'],
          ['Eventually', 'In the end or after some time', 'He eventually achieved success.', 'The rain eventually stopped.', 'She eventually understood the lesson.'],
          ['Evolve', 'To develop or change gradually', 'Technology continues to evolve.', 'His thinking evolved over time.', 'The company evolved into a global brand.'],
          ['Exceed', 'To go beyond a limit or expectation', 'The cost may exceed the budget.', 'Her performance exceeded expectations.', 'Do not exceed the speed limit.'],
          ['Examine', 'To inspect or study carefully', 'The doctor examined the patient.', 'We need to examine the data closely.', 'The teacher examined our answers.'],
          ['Expansion', 'The process of becoming larger', 'The company plans international expansion.', 'The expansion of technology changed lives.', 'Road expansion reduced traffic.'],
          ['Gesture', 'A movement or action expressing meaning', 'His gesture showed respect.', 'She made a friendly gesture.', 'A simple gesture can mean a lot.']
        ];
